### ISSUE TITLE
access local directory assets

### ISSUE THREAD

**Issue by filchristou** [UniStuttgart-IKR/PlutoBoard.jl#12]
I tried adding a background image according to https://tailwindcss.com/docs/background-image#arbitrary-values

But it looks like the server tries to access http://localhost:1234/static/assets/coffee-bg.jpg which doesn't make much sense, since localhost is Pluto.

What is the way forward here ? 

Is this related to the fileserver problem we had before ?

**Comment by Niels1006** [comment]
Added in #15, default serve directory is `static` in the user package. You'd still need to specify the full url `http://localhost:8085/image.png` to get a picture `static/image.png`
